### ISSUE TITLE
login-form-using-the-http-connector

### ISSUE THREAD

**Issue by isuruuy429** [wso2/integration-studio-examples#91]
**Description:**
Once done the Step 6 in **Set Up and Run the Example** section in the web browser, it provides the following output. 

````
body=%0A%09%09%0A%09
````

**Comment by sajithaliyanage** [comment]
As per the note in Readme file https://github.com/wso2/integration-studio-examples/blame/master/migration/mule/login-form-using-the-http-connector/README.md#L44, the user needs to add a custom_message_formatters for `text/html` type in embedded MI deployment.toml since this type doesn't support by default message_formatters. https://github.com/wso2/integration-studio-examples/issues/58
